export const GET_QUESTIONS_REQUEST = "GET_QUESTION_REQUEST";

export const GET_QUESTIONS_SUCCESS = "GET_QUESTION_SUCCESS";

export const GET_QUESTIONS_FAILURE = "GET_QUESTION_FAILURE";

export const GET_QUESTION_DESCRIPTION_REQUEST = "GET_QUESTION_DESCRIPTION_REQUEST";

export const GET_QUESTION_DESCRIPTION_SUCCESS = "GET_QUESTION_DESCRIPTION_SUCCESS";

export const GET_QUESTION_DESCRIPTION_FAILURE = "GET_QUESTION_DESCRIPTION_FAILURE";

export const ASK_QUESTION_REQUEST = "ASK_QUESTION_REQUEST";

export const ASK_QUESTION_SUCCESS = "ASK_QUESTION_SUCCESS";

export const ASK_QUESTION_FAILURE = "ASK_QUESTION_FAILURE";

export const EDIT_REPLY = "EDIT_REPLY";

export const ADD_REPLY_REQUEST = "ADD_REPLY_REQUEST";

export const ADD_REPLY_SUCCESS = "ADD_REPLY_SUCCESS";

export const ADD_REPLY_FAILURE = "ADD_REPLY_FAILURE";